version: '3.8'

services:
  # Development service
  juice-jockey-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    env_file:
      - docker.env
    profiles:
      - dev

  # Production service
  juice-jockey-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - docker.env
    restart: unless-stopped
    profiles:
      - prod

  # Production service with custom port
  juice-jockey-prod-80:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - docker.env
    restart: unless-stopped
    profiles:
      - prod-80

networks:
  default:
    name: juice-jockey-network
